/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEPrivyJobsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getEncryptedJob"
      | "isJobSubmitted"
      | "submitEncryptedJob"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EncryptedJobStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedJob",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJobSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedJob",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJobSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedJob",
    data: BytesLike
  ): Result;
}

export namespace EncryptedJobStoredEvent {
  export type InputTuple = [applicant: AddressLike];
  export type OutputTuple = [applicant: string];
  export interface OutputObject {
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEPrivyJobs extends BaseContract {
  connect(runner?: ContractRunner | null): FHEPrivyJobs;
  waitForDeployment(): Promise<this>;

  interface: FHEPrivyJobsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedJob: TypedContractMethod<[user: AddressLike], [string], "view">;

  isJobSubmitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  submitEncryptedJob: TypedContractMethod<
    [encryptedJob: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedJob"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isJobSubmitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitEncryptedJob"
  ): TypedContractMethod<
    [encryptedJob: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EncryptedJobStored"
  ): TypedContractEvent<
    EncryptedJobStoredEvent.InputTuple,
    EncryptedJobStoredEvent.OutputTuple,
    EncryptedJobStoredEvent.OutputObject
  >;

  filters: {
    "EncryptedJobStored(address)": TypedContractEvent<
      EncryptedJobStoredEvent.InputTuple,
      EncryptedJobStoredEvent.OutputTuple,
      EncryptedJobStoredEvent.OutputObject
    >;
    EncryptedJobStored: TypedContractEvent<
      EncryptedJobStoredEvent.InputTuple,
      EncryptedJobStoredEvent.OutputTuple,
      EncryptedJobStoredEvent.OutputObject
    >;
  };
}
